### ISSUE TITLE
Prevent duplicates in watchlist/backlog

### ISSUE THREAD

**Issue by brian-norman** [Cobresun/movie-club#98]
Right now a user can add a movie that is already in the backlog to the backlog, this should be prevented

**Comment by cole-adams** [comment]
Solved in these commits:
d59805a2ecc48044b71e0924b3914888b7f3298c
9a554ab0d42224dc9efd090989a49735a6a00498
59886e0e3d7f7568d87c6367bf6581672f25abdf
